### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by felexkemboi** [SwahiliBox/swahilibox-events-api#16]
Hello,am new.I would like to know in that Readme, in the step where  I am suppose to `cd develop`   do you mean a branch or a folder in your directory?

**Comment by Rodgers-M** [comment]
Hey, @felexkemboi great to have you here. That should be `git checkout develop` and not cd. Thanks for bringing it up. you can as well update the readme and raise a PR with that update.

**Comment by felexkemboi** [comment]
Thank you.Let me do that

**Comment by Rodgers-M** [comment]
this issue has been resolved by the referenced PR hence closing it.
