### ISSUE TITLE
Why postgres for the backend

### ISSUE THREAD

**Issue by PhillipMwaniki** [SwahiliBox/swahilibox-events-api#2]
What's the motivation to use postgres instead of it's well known partner mysql? Is there a goal it can achieve way better? Can we make the models db technology independent? Maybe use an orm that will abstract this? 😕

**Comment by danielotieno** [comment]
@PhillipMwaniki  Yes, we will use [sequelize orm](http://docs.sequelizejs.com/) and on Postgres why not explore something else than the common ones we know. Actually, I was expecting Mongo than MySQL.

**Comment by PhillipMwaniki** [comment]
We can use https://dbdiagram.io/home to design the ERD. Let's do everything right from the start. We can have different implementations i.e. sql and nosql along way.

**Comment by danielotieno** [comment]
@PhillipMwaniki Amaizing! We are going to do everything from scratch

**Comment by Rodgers-M** [comment]
@PhillipMwaniki great stuff. I think then you can pick up the task of designing the ERD, right?. As for the tables, i think we can still go with 4 as we have the models [here](https://github.com/SwahiliBox/CodeChallenge1Server/tree/master/app/models) in the previous code. 

cc @danielotieno @dessHub

**Comment by PhillipMwaniki** [comment]
Thanks for the directions to the models @Rodgers-M
