### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by dessHub** [SwahiliBox/swahilibox-events-api#29]
# Summary

Docker is container platform use to build, manage and secure applications. Containers allow a developer to package up an application with all of the parts it needs, such as libraries and other dependencies, and ship it all out as one package.

**Comment by Rodgers-M** [comment]
@dessHub before you close this issue, could you please also update the Readme to have a section where someone can run the application using docker.

**Comment by dessHub** [comment]
@Rodgers-M it was included in the PR I opened.
